name: Daily Backup

on:
  schedule:
    - cron: "0 16 * * *"  # Schedule the backup daily at midnight

jobs:
  backup:
    runs-on: ubuntu 22.04  # You can choose other OS options as well

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch and pull changes
        run: |
          git fetch origin
          git pull origin develop
